# Site settings
title: Kali Blog
SEOTitle: Kali 的小站
header-img: img/post-bg-desk.jpg
email: kalierincn@outlook.com
description: "中立最好，学校最坏."
keyword: "Kali Blog, Kali的小站"
url: "https://kalicn.github.io"          # your host, for absolute URL
baseurl: ""      # for example, '/blog' if your blog hosted on 'host/blog'
github_repo: "https://github.com/kalicn/kalicn.github.io.git" # you code repository

# Sidebar settings
sidebar: true                           # whether or not using Sidebar.
sidebar-about-description: "与其看教科书，还不如读Linux源码。"
sidebar-avatar: /img/yeswecode.jpg      # use absolute URL, seeing it's used in both `/` and `/about/`



# SNS settings
RSS: true
github_username:    kalicn





# Build settings
# from 2016, 'pygments' is unsupported on GitHub Pages. Use 'rouge' for highlighting instead.
permalink: pretty
paginate: 13
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
anchorjs: true                          # if you want to customize anchor. check out line:181 of `post.html`



# Gems
# from PR#40, to support local preview for Jekyll 3.0
gems: [jekyll-paginate,jemoji,jekyll-sitemap]




# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM                            # use Github Flavored Markdown !important



# 评论系统
# Gitalk
gitalk:
  enable: true   #是否开启Gitalk评论
  clientID: 5943aeedd7ee1a1cbdf7        # 嘿，别乱看我的秘密                #生成的clientID
  clientSecret: 4ffbc9e4eb8b6aef2b390b2bda69ed6a744c5c07    #生成的clientSecret
  repo: kalicn.github.io    #仓库名称
  owner: kalicn    #github用户名
  admin: kalicn
  distractionFreeMode: false #是否启用类似FB的阴影遮罩
  perPage: 15


# 统计

# Analytics settings
# Baidu Analytics
ba_track_id: 4383e168cd44bd4eeedaa34229a603c5

ga_track_id: 'UA-171298607-1'
ga_domain: auto






# Featured Tags
featured-tags: true                     # 是否使用首页标签
featured-condition-size: 1             # 相同标签数量大于这个数，才会出现在首页


# Friends
friends: [
    {
        title: "七夏浅笑",
        href: "http://julydate.com/"
    },{
        title: "可视化",
        href: "https://gujiayu7676.github.io/"

    },{
        title: "Jiyiren.Blog",
        href: "https://jiyiren.github.io/"
    },{
        title: "由我管理的NoSchoolBlog",
        href: "https://kalicn.github.io/noschoolblog/"
    },{
        title: "Tianhaoo的博客",
        href: "https://tianhaoo.github.io/"
    }    
]
